### ISSUE TITLE
加载注册物品时报错

### ISSUE THREAD

**Issue by dandanlong123** [ItsFlicker/SlimefunItemExpansion#1]
SlimefunItemExpansion] Enabling SlimefunItemExpansion v1.0-SNAPSHOT
[08:11:02 INFO]: [SlimefunItemExpansion] 读取配置文件中...
[08:11:02 INFO]: [SlimefunItemExpansion] 注册SlimeFun物品中...
[08:11:02 ERROR]: Error occurred while enabling SlimefunItemExpansion v1.0-SNAPSHOT (Is it up to date?)
[08:11:02 ERROR]: Suspected Plugins:
[08:11:02 ERROR]:       SlimefunItemExpansion{enabled,ver=1.0-SNAPSHOT,path=plugins/SlimefunItemExpansion-1.0-SNAPSHOT (1).jar}
[08:11:02 ERROR]: Exception details below:
java.lang.NoSuchMethodError: 'void io.github.thebusybiscuit.slimefun4.api.items.ItemSetting.<init>(java.lang.String, java.lang.Object)'
        at com.wlyscraft.slimefunitemexpansion.items.MouseTail.<init>(MouseTail.java:19) ~[?:?]
        at com.wlyscraft.slimefunitemexpansion.tasks.ItemRegisterTask.run(ItemRegisterTask.java:97) ~[?:?]
        at com.wlyscraft.slimefunitemexpansion.SlimefunItemExpansion.onEnable(SlimefunItemExpansion.java:47) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-96]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-96]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-96]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-96]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-96]
        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:593) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-96]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:303) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-96]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1074) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-96]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-96]
        at java.lang.Thread.run(Thread.java:834) [?:?]
[08:11:02 INFO]: [SlimefunItemExpansion] Disabling SlimefunItemExpansion v1.0-SNAPSHOT

运行环境:
> sf versions
[08:16:38 INFO]: Slimefun 运行的服务器环境:
Yatopia git-Yatopia-ver/1.16.5-96 (MC: 1.16.5)
Slimefun 1.0.2_ByXzavier0722
Metrics-组件 #21
Java 11

安装的附属插件: (34)
  ExtraTools vDEV - 26 (git 0cb2ad70)
  FoxyMachines v1.0.0
  SlimefunOreChunks vDEV - 13 (git 9f7a2be3)
  SensibleToolbox vUNOFFICIAL
  Bump v1.0
  DynaTech v1.0.0
  ExtraGear vDEV - 12 (git 4570ea2c)
  ClayTech v1.2.21
  InfinityExpansion vDEV - 100 (git 65892de0)
  ElectricSpawners vUNOFFICIAL                                                       SlimyTreeTaps vDEV - 18 (git ab11a282)
  PrivateStorage vUNOFFICIAL                                                         TranscEndence vDEV - 23 (git c7ddc06a)
  ColoredEnderChests vDEV - 21 (git 2d3a859d)
  NewBegginings v1.0.0
  GeneticChickengineering vDEV - 12 (git 8912d443)
  FluffyMachines vDEV - 72 (git f2ad968f)                                            ChestTerminal vUNOFFICIAL
  PomaExpansion vUNOFFICIAL
  SlimefunItemExpansion v1.0-SNAPSHOT
  Residence v4.9.3.3
  SlimefunWarfare vUNOFFICIAL
  EcoPower vDEV - 1 (git 53445ee5)
  SlimefunLuckyBlocks vUNOFFICIAL                                                    SlimefunZT v1.0-SNAPSHOT
  ExoticGarden vDEV - 75 (git 6c3e5412)
  Liquid vDEV - 10 (git 2277a85b)
  SlimeCustomizer vDEV - 4 (git daae21f7)
  LiteXpansion v1.0.0
  SimpleUtils vDEV - 3 (git ee043364)
  MagicXpansion v0.1.0
  SoulJars vUNOFFICIAL
  EnergyTools v0.1-alpha_test
  SlimyRepair v1.0.0

没有完整注册所有物品然后报错就在这了

**Comment by ItsFlicker** [comment]
已修复
(真没想到这插件会有人用)

**Comment by dandanlong123** [comment]
好东西啊为什么没人用

**Comment by ItsFlicker** [comment]
本来是只准备给自己的服务器用的
对了 你这个粘液科技版本是什么
