### ISSUE TITLE
造石机1和2无法使用

### ISSUE THREAD

**Issue by haiman233** [ItsFlicker/SlimefunItemExpansion#2]
造石机无法使用，放下后过段时间就会消失
粘液版本:RC－24
java版本:Java16
mc版本:1.17
报错:
Block Info:
  World: jm
  X: -318
  Y: 51
  Z: 52
  Material: PLAYER_HEAD
  Block Data: org.bukkit.craftbukkit.v1_17_R1.block.impl.CraftSkullPlayer
  State: org.bukkit.craftbukkit.v1_17_R1.block.CraftSkull

Ticker-Info:
  Type: Asynchronous

Slimefun Data:
  ID: IE_COBBLESTONE_GENERATOR
  Inventory: true
  Data: {"energy-charge":"256","id":"IE_COBBLESTONE_GENERATOR"}
Stacktrace:

java.lang.IllegalArgumentException: The Ingredients array cannot be empty or null
	at org.apache.commons.lang.Validate.notEmpty(Validate.java:212)
	at io.github.thebusybiscuit.slimefun4.implementation.operations.CraftingOperation.<init>(CraftingOperation.java:30)
	at io.github.thebusybiscuit.slimefun4.implementation.operations.CraftingOperation.<init>(CraftingOperation.java:26)
	at me.mrCookieSlime.Slimefun.Objects.SlimefunItem.abstractItems.AContainer.tick(AContainer.java:370)
	at me.mrCookieSlime.Slimefun.Objects.SlimefunItem.abstractItems.AContainer$3.tick(AContainer.java:336)
	at io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.tickBlock(TickerTask.java:180)
	at io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.tickLocation(TickerTask.java:167)
	at io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.tickChunk(TickerTask.java:137)
	at io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.run(TickerTask.java:106)
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100)
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)

**Comment by ItsFlicker** [comment]
明天修（
顺便来一次大升级

**Comment by haiman233** [comment]
升级会增加新物品吗ovo

**Comment by ItsFlicker** [comment]
主要是重构了下代码
加了个语言文件
加了点特性
你想要啥物品(

**Comment by haiman233** [comment]
比如说老八之剑（打人给予敌人霉运效果）
金钟罩（给予一小段时间抗性提升5）😜

**Comment by ItsFlicker** [comment]
草(一种植物)
终于修好了
sb Slimefun 乱改
最后用了unsafeInstance才解决
下个版本再加新物品了(

**Comment by haiman233** [comment]
好耶，谢谢

**Comment by ItsFlicker** [comment]
你开的是啥服啊

**Comment by haiman233** [comment]
粘液科技

**Comment by haiman233** [comment]
ovo正在收集附属呢

**Comment by haiman233** [comment]
现在目前是4面粘液ovo

**Comment by ItsFlicker** [comment]
![image](https://user-images.githubusercontent.com/34670283/127878133-1f794f50-ad35-4df4-a5c8-b766c5321459.png)
推不上去 服了

**Comment by haiman233** [comment]
az
话说您在粘液科技的qq群吗 807302496

**Comment by ItsFlicker** [comment]
不在啊= = 
我加下

**Comment by haiman233** [comment]
好耶，又一位大佬

**Comment by ItsFlicker** [comment]
1.0.0 已发布
